# Generated by Django 4.2.11 on 2024-05-16 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categorey_listing_isactive_listing_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='listwatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
