# Generated by Django 4.2.11 on 2024-06-14 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('author', models.ManyToManyField(blank=True, null=True, related_name='UserComment', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ManyToManyField(blank=True, null=True, related_name='listingData', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
