# Generated by Django 4.2.11 on 2024-06-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='listing',
            field=models.ManyToManyField(blank=True, null=True, related_name='listingData', to='auctions.listing'),
        ),
    ]
