# Generated by Django 4.2.11 on 2024-06-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bid_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorey',
            name='categoreyName',
            field=models.CharField(max_length=200),
        ),
    ]
